defaults:
  - /envs/quadruped_walk@env

method:
  _target_: stable_baselines3.SAC

  learning_rate: 1.0e-4
  batch_size: 1024
  ent_coef: "auto_0.1"
  target_update_interval: 2
  tau: 0.005
  gamma: 0.99
  learning_starts: 5000

  device: cpu
  policy_kwargs:
    net_arch: [1024, 1024]
    n_critics: 2
