defaults:
  - default
  - preset: ???
  - _self_

training:
  seed: 0
  total_timesteps: 1_000_000
  num_envs: 16

logging:
  tags: []
  group: null
  checkpoint_freq: 100_000
  eval_freq: 10_000
  stats_window_size: ${training.num_envs}
