defaults:
  - default
  - preset: ???
  - _self_

training:
  seed: 0
  total_timesteps: 1_000_000
  num_envs: 16

logging:
  tags: []
  group: null
  eval_freq: 4_000
  n_eval_episodes: 5
  save_best_eval_models: false
  save_checkpoints: false
  checkpoint_freq: 100_000
