defaults:
  - env: quadruped_walk
  - _self_

hydra:
  job:
    chdir: true

method: ${env.method}

training:
  total_timesteps: 1_000_000
  seed: 0
  num_envs: 16

logging:
  project: "pref_rl"
  tags: ["baseline"]
  checkpoint_freq: 100_000
  eval_freq: 10_000
