method:
  pref:
    n_steps_reward: 32_000
    ann_buffer_size_eps: null
    sampler: entropy
    segment_size: 50
    max_feed: 2_000
    feed_batch_size: 200

    teacher: oracle  # One of oracle, stoc, mistake, skip, equal, myopic

    # Can also set individual teacher parameters by commenting in below:
    # teacher_kwargs:
    #   beta: .inf
    #   gamma: 1
    #   eps_mistake: 0
    #   eps_equal: 0
    #   eps_skip: 0
