method:
  pref:
    device: cpu

    ann_buffer_size_eps: 100
    segment_size: 50

    schedule:
      _target_: pref_rl.utils.train_schedules.BasePrefSchedule
      n_steps_reward: 32_000
      max_feed: 2_000
      feed_batch_size: 200

    sampler: uniform
    sampler_kwargs:
      uniform_fraction: 0.0
    sample_uniform_on_first_train: true

    teacher: oracle  # One of oracle, stoc, mistake, skip, equal, myopic

    # Can also set individual teacher parameters by commenting in below:
    # teacher_kwargs:
    #   beta: .inf
    #   gamma: 1
    #   eps_mistake: 0
    #   eps_equal: 0
    #   eps_skip: 0

    validate_on_train: false
    validate_on_current: true
    n_steps_eval_current: 32_000
    validate_on_held_out: true
    held_out_data_path: data/validation_data.pkl

    synth_buffer_size: 0
    synth_schedule: null
      # _target_: pref_rl.utils.train_schedules.BasePrefSchedule
      # n_steps_reward: 32_000
      # max_feed: null
      # feed_batch_size: 200
      # n_steps_first_train: 352_000
