method:
  pref:
    device: cpu

    n_steps_reward: 32_000
    ann_buffer_size_eps: 100
    segment_size: 50
    max_feed: 2_000
    feed_batch_size: 200

    sampler: disagreement
    sampler_kwargs:
      uniform_fraction: 0.0

    teacher: oracle  # One of oracle, stoc, mistake, skip, equal, myopic

    # Can also set individual teacher parameters by commenting in below:
    # teacher_kwargs:
    #   beta: .inf
    #   gamma: 1
    #   eps_mistake: 0
    #   eps_equal: 0
    #   eps_skip: 0

    validate_on_train: false
    validate_on_current: true
    n_steps_eval_current: 32_000
    validate_on_held_out: true
    held_out_data_path: data/validation_data.pkl

    synth_ratio: 0.0
    synth_start_step: 0
    synth_stop_step: 1_000_000
    synth_buffer_size: 100_000
    synth_teacher_kwargs:
      limit_old_recent_steps: 100000
      limit_new_recent_steps: 50000
      weight_scheme: 'constant'
      max_weight: 0.5
      sampling_method: 'uniform'
